{% set name = "pysignal" %}
{% set version = "1.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dgovil/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 499c9ae52a0ab83173fa469ffc86a32cc97ff51bc840f184d83bde754746425a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - PySignal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dgovil/PySignal
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Signal Library to mimic the Qt Signal system for event driven connections

  description: |
    A Qt style signal implementation that doesn't require QObjects.
    This supports class methods, functions, lambdas and partials.

    Signals can either be created on the instance or on the class, and
    can be handled either as objects or by string name. Unlike PyQt
    signals, PySignals do not enforce types by default as I believe this
    is more pythonic.
  dev_url: https://github.com/dgovil/PySignal

extra:
  recipe-maintainers:
    - mtsolmn
